### ISSUE TITLE
希望能和师傅交流~

### ISSUE THREAD

**Issue by Ph0rse** [zhl2008/awd-platform#2]
haozi师傅你好，之前受您这个项目启发，自己开发了一个awd的框架，准备在11月末开源。想和师傅交流一下关于awd训练环境自动生成框架的相关知识点，以及不太清楚新框架在使用过程中中。如果用了您这里的比赛源码（如湖湘杯），会不会构成侵权等问题。求交流，QQ：2717440643，或者您给个联系方式也行~
新的框架是公益性的，新增了pwn和平台。整体代码和这个项目相差很大，但思路启发于这个项目。也想交流一下，看有没有共同开发的可能。谢谢

**Comment by zhl2008** [comment]
woc, u should already have my WECHAT
