### ISSUE TITLE
Boot failure

### ISSUE THREAD

**Issue by qing-root** [zhl2008/awd-platform#5]
Unable to find image 'web_14.04:latest' locally
docker: Error response from daemon: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers).

**Comment by zhl2008** [comment]
git pull zhl2008/web_14.04

**Comment by ValerieHu1995** [comment]
docker pull zhl2008/web_14.04
